services:
  postgres:
    image: postgres:16.4
    container_name: oauth_provider_db
    ports:
      - 5432:5432
    volumes:
      - ./oauth_provider_service/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=oauth_provider
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
  oauth-provider-service:
    image: python:3.9-slim
    volumes:
      - ./oauth_provider_service:/app
      - type: bind
        source: ./requirements.txt
        target: /requirements.txt
        read_only: true
    working_dir: /app
    ports:
      - "5000:5000"
    command: >
      sh -c "pip install --upgrade pip && pip install -r /requirements.txt && sleep 30 && flask db stamp head && flask db migrate && flask db upgrade && python app.py"
    depends_on:
      - postgres
  company-a-service:
    image: python:3.9-slim
    volumes:
      - ./company_a_service:/app
      - type: bind
        source: ./requirements.txt
        target: /requirements.txt
        read_only: true
    working_dir: /app
    ports:
      - "5001:5000"
    command: >
      sh -c "pip install --upgrade pip && pip install -r /requirements.txt && sleep 30 && python app.py"
    depends_on:
      - postgres
  company-b-service:
    image: python:3.9-slim
    volumes:
      - ./company_b_service:/app
      - type: bind
        source: ./requirements.txt
        target: /requirements.txt
        read_only: true
    working_dir: /app
    ports:
      - "5002:5000"
    command: >
      sh -c "pip install --upgrade pip && pip install -r /requirements.txt && sleep 30 && python app.py"
    depends_on:
      - postgres